# Generated by Django 3.2.7 on 2021-10-08 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('caixa_de_selecao', 'Caixa de seleção'), ('resposta_curta', 'Resposta Curta'), ('paragrafo', 'Parágrafo')], max_length=255)),
                ('enunciado', models.CharField(max_length=255)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.questao')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
