# Generated by Django 3.2.7 on 2021-10-08 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='usuarios',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
